### ISSUE TITLE
使用Ansible执行时，在 name: Generate report file 调用 ansible.builtin.template 时报错

### ISSUE THREAD

**Issue by adiooooos** [liushiju/ansible-HealthCheck#2]
报错信息如下所示，请问这是怎么引起的呢？
[error.txt](https://github.com/liushiju/ansible-HealthCheck/files/15282316/error.txt)

TASK [os-check : Generate report file.] ****************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: </html>. Could not load "get_check_data": 'get_check_data'
fatal: [Test-RHEL-7.9-1]: FAILED! => {"changed": false, "msg": "AnsibleError: template error while templating string: Could not load \"get_check_data\": 'get_check_data'. String: {% set data =  hostvars | get_check_data %}\n<!DOCTYPE html>\n<html lang=\"en\" style=\"outline: none; box-sizing: inherit; margin: 0; padding: 0; --blue: #324cdd; --indigo: #6610f2; --purple: #6f42c1; --pink: #e83e8c; --red: #ec0c38; --orange: #fd7e14; --yellow: #fa3a0e; --green: #2dce89; --teal: #00A9A2; --cyan: #11cdef; --white: #fff; --gray: #f7fafc; --gray-dark: #333333; --primary: #7571f9; --secondary: #9097c4; --success: #6fd96f; --info: #4d7cff; --warning: #f29d56; --danger: #ff5e5e; --light: #f8f9fa; --dark: #333333; --breakpoint-xs: 0; --breakpoint-sm: 576px; --breakpoint-md: 768px; --breakpoint-lg: 992px; --breakpoint-xl: 1200px; --breakpoint-xxl: 1400; --font-family-sans-serif: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'; --font-family-monospace: SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace; font-family: sans-serif; line-height: 1.15; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; -ms-overflow-style: scrollbar; -webkit-tap-highlight-color: rgba(0, 0, 0, 0);\">\n<head>\n    <meta charset=\"utf-8\">\n    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n    <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n    <title>巡检报告-{{ data.time }}</title>\n\t<style type=\"text/css\">\n@media (min-width: 576px) {\n  .container {\n    max-width: 540px;\n  }\n}\n@media (min-width: 768px) {\n  .container {\n    max-width: 720px;\n  }\n}\n@media (min-width: 992px) {\n  .container {\n    max-width: 960px;\n  }\n}\n@media (min-width: 1200px) {\n  .container {\n    max-width: 1140px;\n  }\n}\n@media (min-width: 576px) {\n  .col-sm {\n    flex-basis: 0;\n    flex-grow: 1;\n    max-width: 100%;\n  }\n\n  .col-sm-auto {\n    flex: 0 0 auto;\n    width: auto;\n    max-width: none;\n  }\n\n  .col-sm-1 {\n    flex: 0 0 8.33333%;\n    max-width: 8.33333%;\n  }\n\n  .col-sm-2 {\n    flex: 0 0 16.66667%;\n    max-width: 16.66667%;\n  }\n\n  .col-sm-3 {\n    flex: 0 0 25%;\n    max-width: 25%;\n  }\n\n  .col-sm-4 {\n    flex: 0 0 33.33333%;\n    max-width: 33.33333%;\n  }\n\n  .col-sm-5 {\n    flex: 0 0 41.66667%;\n    max-width: 41.66667%;\n  }\n\n  .col-sm-6 {\n    flex: 0 0 50%;\n    max-width: 50%;\n  }\n\n  .col-sm-7 {\n    flex: 0 0 58.33333%;\n    max-width: 58.33333%;\n  }\n\n  .col-sm-8 {\n    flex: 0 0 66.66667%;\n    max-width: 66.66667%;\n  }\n\n  .col-sm-9 {\n    flex: 0 0 75%;\n    max-width: 75%;\n  }\n\n  .col-sm-10 {\n    flex: 0 0 83.33333%;\n    max-width: 83.33333%;\n  }\n\n  .col-sm-11 {\n    flex: 0 0 91.66667%;\n    max-width: 91.66667%;\n  }\n\n  .col-sm-12 {\n    flex: 0 0 100%;\n    max-width: 100%;\n  }\n\n

**Comment by adiooooos** [comment]
提示 AnsibleError: template error while templating string: Could not load \"get_check_data\": 'get_check_data'. String: {% set data =  hostvars | get_check_data %}；
然后我寻找这个变量 # more os-check/templates/report-cssinline.html | grep get_check_data
{% set data =  hostvars | get_check_data %}
请问接下来该在哪儿修改呢？

**Comment by adiooooos** [comment]
应该是缺少 hostvars 这个文件

**Comment by adiooooos** [comment]
再补充下，我在ansible.cfg里 添加了
[defaults]
enable_plugins = filter_plugins
继续相同的报错

**Comment by liushiju** [comment]
修改ansible.cfg中配置，指定filter_plugins地址
filter_plugins     =  filter_plugins

**Comment by adiooooos** [comment]
@liushiju big thanks, the issue solved 非常感谢，我后续可以根据您的在report里加入top10 进程状态吗？

**Comment by adiooooos** [comment]
补充下，在用ansible-navigator在Automation Controller UI界面上执行时，会在folder下无法找到roles/os-check.yml， 只有改名为vars/main.yml以后，才能执行成功

**Comment by adiooooos** [comment]
再次补充下，在Ansible core下执行时是成功并能在邮件里能看到正常的UI report。在ansible tower上，使用EE容器运行时，会报语言的错误，具体报错信息如下所示：
![image](https://github.com/liushiju/ansible-HealthCheck/assets/42025465/35c63e5e-67bb-4da3-a8c3-0642b1999862)

**Comment by adiooooos** [comment]
上述问题全部解决，RCA：The reason for this error is "C.utf8" locale directory is not available on RHEL7 and below systems which results job templates to fail；
解决方案：重新打包EE镜像，、
[root@controller safety-patrol]# more execution-environment.yml
---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest
  EE_BUILDER_IMAGE: registry.redhat.io/ansible-automation-platform-24/ansible-builder-rhel8:latest

ansible_config: ansible.cfg

dependencies:
  galaxy: requirements.yml

additional_build_steps:
  append:
  - RUN microdnf install -y glibc-langpack-en; sed -i 's/^LANG=.*/LANG="en_US.utf8"/' /etc/locale.conf; sed -i 's/^LC_ALL=.*/LC_ALL="en_US.utf8"/' /etc/locale.conf
  - ENV LANG=en_US.utf8
  - ENV LC_CTYPE=en_US.utf8
  - ENV LC_ALL=en_US.utf8
